### ISSUE TITLE
metadata

### ISSUE THREAD

**Issue by sonn-gamm** [afincato/tekken#1]
Looking back at how I tried to organise projects' informations, and to how I'd like to move forward, there is a bit of a struggle between keeping the text file purely markdown, and possibly the need to add extra bits as YAML formatted data.

For example, I began storing in the text file stuff like `status`, `start date` and `end date`, `type` (client work, personal project) and `collaborators`.

In thinking that this text will be converted to an html page at some point, I initially divided the file into key-pair values, kirby style:

```
title: xx
----
status: xx
----
period: 
  - start: 22-08-2017
     end: ongoing
----
notes:

some markdown
----
tasks:

## section

- [ ] task
```

etc.

Now, I'm thinking that maybe we can fit this metadata as a YAML block right after the file's title, like so:

```
# project title

status: xx
period: 
  - start: 22-08-2017
     end: ongoing

Notes notes notes notes:

- one
- two
- three

## section d(20-07-2018)

- [ ] xxx

etc
```

I think there might be a way to demarcate the YAML block somehow outside of the markdown, if that would be helpful then for the parser to take up those infos as well. Or we can just look for specific words and following values after the colon?

The general feeling here is to move away from those four dashes key-pair value demarcation, and just write whatever mix of notes, tasks, and other bits of informations (like metadata) in the file as *freely* as possible, and meanwhile agreeing upon certain keywords that make the parser build a well formed tree structure.

What do you think?
